### ISSUE TITLE
Update library SDK version

### ISSUE THREAD

**Issue by mio9** [jangxx/node-vjoy#4]
The library is currently built upon 544 while a more recent version has released and is installed on my machine
![image](https://user-images.githubusercontent.com/11581624/95557282-8bdad280-0a4f-11eb-9c40-ac15f7074dd3.png)

**Comment by jangxx** [comment]
Thanks for bringing this to my attention. I have just published a new version to npm which includes the new SDK.

**Comment by mio9** [comment]
thank you very much, your work is highly appreciated :D
